In [1]:
import numpy as np

In [8]:
a = np.array([[1,2],[2,1],[0,0]])
np.argsort(-a)

array([[1, 0],
       [0, 1],
       [0, 1]])

In [3]:
for i, j in enumerate(a):
    print(i, j)

0 1
1 2
2 0


In [10]:
a.squeeze()

array([[1, 2],
       [2, 1],
       [0, 0]])

In [9]:
a.sum()

6

In [11]:
a.shape[0]

3

In [14]:
a[0].sum()

3

In [16]:
import torch as t

In [17]:
b = t.tensor([], requires_grad=True)

In [18]:
b

tensor([], requires_grad=True)

In [19]:
b.append(1)

AttributeError: 'Tensor' object has no attribute 'append'

In [26]:
t.ones(3).mean()

tensor(1.)

In [25]:
for i, (j, k) in enumerate(zip(range(3), range(2, 5))):
    print(i, j, k)

0 0 2
1 1 3
2 2 4


In [27]:
a

array([[1, 2],
       [2, 1],
       [0, 0]])

In [28]:
b = t.tensor([1,2,3, -1,7])
boo = t.where(b > 1)
boo

(tensor([1, 2, 4]),)

In [40]:
(a >= 2).mul(a).sum().div(sum(a>=2).item())

AttributeError: 'numpy.ndarray' object has no attribute 'mul'

In [38]:
sum(b>2).item()

2

In [41]:
b = t.tensor([[1,2],[2,1],[0,0]])

In [43]:
(b > 1).mul(b).sum().div(2)

tensor(2)

In [48]:
(b>1).sum().item()

2